
require:
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 2.7

Naming/MethodParameterName:
  MinNameLength: 1

Style/BlockComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Layout/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20
